FROM mcr.microsoft.com/playwright:v1.59.1-jammy

RUN apt-get update && apt-get install -y python3-pip 

# Set up the working directory first
WORKDIR /workspace

# Create a virtual environment and install the OpenTF agent safely
# RUN python3 -m venv /opt/venv
# ENV PATH="/opt/venv/bin:$PATH"
RUN pip install opentf-agent
RUN npm install dotenv --save
RUN npm install -D @playwright/test
