name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install chromium
    - name: Run Playwright tests
      env:
        FRONTEND_GAMITOOL: ${{ vars.FRONTEND_GAMITOOL }}
        BACKEND_GAMITOOL: ${{ vars.BACKEND_GAMITOOL }}
        TENANT: ${{vars.TENANT}}
        SQUASH_QA_TOKEN: ${{secrets.SQUASH_QA_TOKEN}}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 14
