name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install chromium --only-shell
    - name: Run Playwright tests
      env:
        FRONTEND_GAMITOOL: ${{ vars.FRONTEND_GAMITOOL }}
        BACKEND_GAMITOOL: ${{ vars.BACKEND_GAMITOOL }}
        TENANT: ${{vars.TENANT}}
        SQUASH_QA_TOKEN: ${{secrets.SQUASH_QA_TOKEN}}
      run: npx playwright test
    - name: load test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Build test report
      uses: simple-elf/allure-report-action@v1.13
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results
        # name: html-report--attempt-${{ github.run_attempt }}
        # path: playwright-report
        # retention-days: 14
    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history